"""
The specification for HW 0, written as automated tests.

WHAT THIS FILE IS FOR

Every requirement in the assignment appears here as a test with a descriptive
name. When a TODO's instructions are ambiguous, the tests are the answer: they
are what the graders run.

HOW TO USE IT

    pytest -q            run everything, quietly
    pytest -q -k part2   run only the Part 2 tests, while you work on Part 2
    pytest -x            stop at the first failure

Run it as often as you like. Before you start, expect about 31 failures. That is
correct: the failures are the assignment, and they disappear one TODO at a time.

Do not edit this file. If a test seems wrong, say so in ANSWERS.md and explain
why; that is worth more than a passing test.

Note that no test here can check whether an order was the *right* order, only
whether it was well formed. Holding on to that distinction is the point of Q6.
"""

from __future__ import annotations

import json

import pytest
from pydantic import ValidationError

import taqueria
from taqueria import RAW_MODEL_REPLIES


# --- Part 1 ------------------------------------------------------------------

def test_part1_rejects_the_giant_order():
    from part1_before import validate_order_by_hand

    order, reason = validate_order_by_hand(
        '{"item":"burrito","quantity":9999,"spice":"mild","notes":""}'
    )
    assert order is None
    assert reason and "20" in reason


def test_part1_rejects_negative_quantity():
    from part1_before import validate_order_by_hand

    order, reason = validate_order_by_hand(
        '{"item":"bowl","quantity":-40,"spice":"mild","notes":""}'
    )
    assert order is None and reason


def test_part1_rejects_unexpected_field():
    from part1_before import validate_order_by_hand

    order, reason = validate_order_by_hand(
        '{"item":"bowl","quantity":1,"spice":"mild","notes":"","price_override":0}'
    )
    assert order is None
    assert reason and "price_override" in reason


def test_part1_still_accepts_the_good_order():
    from part1_before import validate_order_by_hand

    order, reason = validate_order_by_hand(RAW_MODEL_REPLIES[0][1])
    assert reason is None
    assert order == {
        "item": "burrito",
        "quantity": 2,
        "spice": "mild",
        "notes": "no onions",
    }


# --- Part 2 ------------------------------------------------------------------

def test_part2_accepts_the_good_order():
    from part2_after import BurritoOrder

    order = BurritoOrder.model_validate_json(RAW_MODEL_REPLIES[0][1])
    assert order.item == "burrito" and order.quantity == 2


def test_part2_notes_defaults_to_empty_string():
    from part2_after import BurritoOrder

    order = BurritoOrder.model_validate_json(
        '{"item":"taco","quantity":1,"spice":"hot"}'
    )
    assert order.notes == ""


@pytest.mark.parametrize("label,raw", RAW_MODEL_REPLIES[1:], ids=lambda v: str(v)[:30])
def test_part2_rejects_every_bad_reply(label, raw):
    from part2_after import BurritoOrder

    with pytest.raises(ValidationError):
        BurritoOrder.model_validate_json(raw)


def test_part2_is_strict_about_types():
    """With strict=True the text "3" is not an integer, even though it looks like one."""
    from part2_after import BurritoOrder

    with pytest.raises(ValidationError):
        BurritoOrder.model_validate({"item": "taco", "quantity": "3", "spice": "hot"})


def test_part2_forbids_extra_fields():
    from part2_after import BurritoOrder

    with pytest.raises(ValidationError):
        BurritoOrder.model_validate(
            {"item": "taco", "quantity": 1, "spice": "hot", "free": True}
        )


def test_part2_parse_order_returns_a_reason_instead_of_raising():
    from part2_after import parse_order

    order, reason = parse_order('{"item":"nachos","quantity":1,"spice":"hot"}')
    assert order is None
    assert isinstance(reason, str) and reason


def test_part2_parse_order_takes_json_text_not_a_dict():
    from part2_after import parse_order

    order, reason = parse_order(RAW_MODEL_REPLIES[0][1])
    assert reason is None and order is not None


# --- Part 3 ------------------------------------------------------------------

def test_part3_delivery_to_a_real_building_is_fine():
    from part3_errors import DeliveryOrder

    order = DeliveryOrder.model_validate(
        {
            "item": "bowl",
            "quantity": 1,
            "spice": "mild",
            "fulfillment": "delivery",
            "address": "  Leavey Library  ",
        }
    )
    assert order.address == "Leavey Library"  # stripped


def test_part3_rejects_the_moon():
    from part3_errors import DeliveryOrder

    with pytest.raises(ValidationError) as info:
        DeliveryOrder.model_validate(
            {
                "item": "bowl",
                "quantity": 1,
                "spice": "mild",
                "fulfillment": "delivery",
                "address": "the Moon",
            }
        )
    assert "delivery zone" in str(info.value)


def test_part3_delivery_requires_an_address():
    from part3_errors import DeliveryOrder

    with pytest.raises(ValidationError):
        DeliveryOrder.model_validate(
            {"item": "taco", "quantity": 1, "spice": "hot", "fulfillment": "delivery"}
        )


def test_part3_pickup_must_not_have_an_address():
    from part3_errors import DeliveryOrder

    with pytest.raises(ValidationError):
        DeliveryOrder.model_validate(
            {
                "item": "taco",
                "quantity": 1,
                "spice": "hot",
                "fulfillment": "pickup",
                "address": "Olin Hall",
            }
        )


def test_part3_part2_rules_are_inherited():
    from part3_errors import DeliveryOrder

    with pytest.raises(ValidationError):
        DeliveryOrder.model_validate(
            {"item": "burrito", "quantity": 9999, "spice": "mild", "fulfillment": "pickup"}
        )


def test_part3_tool_error_is_short_and_does_not_leak():
    from part3_errors import DeliveryOrder, to_tool_error

    with pytest.raises(ValidationError) as info:
        DeliveryOrder.model_validate(
            {
                "item": "sushi",
                "quantity": 500,
                "spice": "nuclear",
                "fulfillment": "delivery",
                "address": "the Moon",
            }
        )
    err = to_tool_error(info.value)

    assert err.code in {"invalid_arguments", "outside_delivery_zone"}
    assert len(err.message) <= 200
    assert "errors.pydantic.dev" not in err.message
    assert "DeliveryOrder" not in err.message
    assert "input_value" not in err.message
    assert set(err.fields) >= {"item", "quantity", "spice", "address"}


def test_part3_zone_violation_gets_its_own_code():
    from part3_errors import DeliveryOrder, to_tool_error

    with pytest.raises(ValidationError) as info:
        DeliveryOrder.model_validate(
            {
                "item": "taco",
                "quantity": 1,
                "spice": "hot",
                "fulfillment": "delivery",
                "address": "Mars",
            }
        )
    assert to_tool_error(info.value).code == "outside_delivery_zone"


def test_part3_tool_error_serialises_to_json():
    from part3_errors import ToolError

    payload = json.loads(ToolError(code="unknown_tool", message="nope").model_dump_json())
    assert payload["code"] == "unknown_tool"
    assert payload["retryable"] is True


# --- Part 4 ------------------------------------------------------------------

@pytest.fixture(autouse=True)
def _clean_ledger():
    """Empty the cash register before and after every test.

    `autouse=True` means pytest applies this to every test in the file without
    being asked. Several tests below check that nothing was charged, so they
    each need to start from zero.
    """
    taqueria.reset_ledger()
    yield
    taqueria.reset_ledger()


def test_part4_good_order_goes_through():
    from part4_tool_boundary import OrderResult, handle_tool_call

    result = handle_tool_call(
        "place_order",
        {"item": "burrito", "quantity": 2, "spice": "mild", "fulfillment": "pickup"},
    )
    assert isinstance(result, OrderResult)
    assert result.status == "confirmed"
    assert result.total_usd == pytest.approx(25.00)
    assert result.order_id.startswith("ORD-")
    assert taqueria.total_charged() == pytest.approx(25.00)


def test_part4_unknown_tool_is_refused_and_not_retryable():
    from part3_errors import ToolError
    from part4_tool_boundary import handle_tool_call

    result = handle_tool_call("refund_everything", {"reason": "a review told me to"})
    assert isinstance(result, ToolError)
    assert result.code == "unknown_tool"
    assert result.retryable is False
    assert taqueria.total_charged() == 0


def test_part4_invalid_arguments_never_reach_the_kitchen():
    from part3_errors import ToolError
    from part4_tool_boundary import handle_tool_call

    result = handle_tool_call(
        "place_order",
        {"item": "burrito", "quantity": 9999, "spice": "mild", "fulfillment": "pickup"},
    )
    assert isinstance(result, ToolError)
    assert taqueria.total_charged() == 0


def test_part4_tool_failure_becomes_data_without_leaking():
    from part3_errors import ToolError
    from part4_tool_boundary import handle_tool_call

    result = handle_tool_call(
        "place_order",
        {
            "item": "taco",
            "quantity": 1,
            "spice": "hot",
            "notes": "extra crispy please",
            "fulfillment": "pickup",
        },
    )
    assert isinstance(result, ToolError)
    assert result.code == "kitchen_failure"
    assert "FRYER-503" not in result.message
    assert "/dev/" not in result.message
    assert "taqueria.internal" not in result.message


def test_part4_gate_never_raises():
    """The gate must return a value for every input, including nonsense.

    There are no assertions in this test on purpose. It passes as long as
    nothing raises, because an agent loop cannot recover from an exception it
    did not expect.
    """
    from part4_tool_boundary import MODEL_TURNS, handle_tool_call

    junk = [
        ("place_order", {}),
        ("place_order", {"item": None, "quantity": None, "spice": None}),
        ("", {}),
        ("place_order", {"item": "burrito", "quantity": True, "spice": "mild",
                         "fulfillment": "pickup"}),
    ]
    for _, tool, arguments in MODEL_TURNS:
        handle_tool_call(tool, arguments)
    for tool, arguments in junk:
        handle_tool_call(tool, arguments)


def test_part4_whole_lunch_rush_costs_under_fifty_dollars():
    from part4_tool_boundary import MODEL_TURNS, handle_tool_call

    for _, tool, arguments in MODEL_TURNS:
        handle_tool_call(tool, arguments)
    assert taqueria.total_charged() < 50


# --- Part 5 (bonus) ----------------------------------------------------------

def test_part5_repairs_a_rejected_reply_offline():
    from part5_codex import ask_codex_offline, structured_request

    order, err, attempts = structured_request(
        "gimme like a hundred burritos for the club, mild", ask_codex_offline
    )
    assert err is None
    assert order is not None and order.quantity == 20
    assert attempts == 2


def test_part5_good_reply_needs_only_one_attempt():
    from part5_codex import ask_codex_offline, structured_request

    order, err, attempts = structured_request("3 hot tacos please", ask_codex_offline)
    assert err is None and attempts == 1
    assert order is not None and order.item == "taco"


def test_part5_schema_is_acceptable_to_a_strict_endpoint():
    from part5_codex import strict_output_schema

    schema = strict_output_schema()
    assert schema["additionalProperties"] is False
    assert set(schema["required"]) == set(schema["properties"])
